// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240304122703_NewRecordLabel")]
    partial class NewRecordLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("Data.Entities.AlbumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordLabelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackList")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordLabelId");

                    b.ToTable("albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Band = "The Beatles",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "47:23",
                            Name = "Abbey Road",
                            Popularity = 3,
                            RecordLabelId = 1,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Come Together, Something, Maxwell's Silver Hammer, Oh! Darling, Octopus's Garden, I Want You (She's So Heavy), Here Comes The Sun, Because, You Never Give Me Your Money, Sun King, Mean Mr. Mustard, Polythene Pam, She Came In Through The Bathroom Window, Golden Slumbers, Carry That Weight, The End, Her Majesty."
                        },
                        new
                        {
                            Id = 2,
                            Band = "Pink Floyd",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "42:49",
                            Name = "The Dark Side of the Moon",
                            Popularity = 4,
                            RecordLabelId = 3,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Speak to Me, Breathe, On the Run, Time, The Great Gig in the Sky, Money, Us and Them, Any Colour You Like, Brain Damage, Eclipse."
                        },
                        new
                        {
                            Id = 3,
                            Band = "Papa Dance",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "57:03",
                            Name = "Nasza Ziemia Eden",
                            Popularity = 2,
                            RecordLabelId = 2,
                            ReleaseDate = new DateTime(1989, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Galaktyczny zwiad, Nasz Disneyland, Temat na clip, It's a simple song, Zły omen, Czas szaleństwa, Nietykalni, Ciało i talent..., Skajlajt, Twój ziemski Eden, The End"
                        },
                        new
                        {
                            Id = 4,
                            Band = "Lady Pank",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "41:27",
                            Name = "Zawsze Tam, Gdzie Ty",
                            Popularity = 3,
                            RecordLabelId = 3,
                            ReleaseDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Dopóki da czas, Przerwa w trasie, Co mnie to obchodzi, Jak igła, Nie omijaj mnie, Niedokończona ulica, Nie wpychaj mnie w to dno, Zawsze tam gdzie ty, Zapłacę każdą cenę, Wiara we wroga"
                        },
                        new
                        {
                            Id = 5,
                            Band = "The Police",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "44:18",
                            Name = "Synchronicity",
                            Popularity = 4,
                            RecordLabelId = 4,
                            ReleaseDate = new DateTime(1983, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Synchronicity I, Walking in Your Footsteps, O My God, Mother, Miss Gradenko, Synchronicity II, Every Breath You Take, King of Pain, Wrapped Around Your Finger, Tea in the Sahara"
                        },
                        new
                        {
                            Id = 6,
                            Band = "Michael Jackson",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "42:19",
                            Name = "Thriller",
                            Popularity = 4,
                            RecordLabelId = 5,
                            ReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Wanna Be Startin' Somethin', Baby Be Mine, The Girl Is Mine, Thriller, Beat It, Billie Jean, Human Nature, P.Y.T. (Pretty Young Thing), The Lady in My Life"
                        },
                        new
                        {
                            Id = 7,
                            Band = "AC/DC",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "42:11",
                            Name = "Back in Black",
                            Popularity = 4,
                            RecordLabelId = 3,
                            ReleaseDate = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackList = "Hells Bells, Shoot to Thrill, What Do You Do for Money Honey, Givin the Dog a Bone, Let Me Put My Love Into You, Back in Black, You Shook Me All Night Long, Have a Drink on Me, Shake a Leg, Rock and Roll Ain't Noise Pollution"
                        });
                });

            modelBuilder.Entity("Data.Entities.RecordLabelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("recordlabel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Starlight Records",
                            Nip = "987654321",
                            Regon = "123456789",
                            Website = "www.starlightrecords.com"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Echo Harmony Music",
                            Nip = "876543219",
                            Regon = "234567891",
                            Website = "www.echoharmonymusic.com"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neon Beat Productions",
                            Nip = "765432198",
                            Regon = "345678912",
                            Website = "www.neonbeatpro.com"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oceanwave Audio",
                            Nip = "654321987",
                            Regon = "456789123",
                            Website = "www.oceanwaveaudio.com"
                        },
                        new
                        {
                            Id = 5,
                            Name = "RetroSound Studios",
                            Nip = "543219876",
                            Regon = "567891234",
                            Website = "www.retrosoundstudios.com"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Aurora Melodies",
                            Nip = "432198765",
                            Regon = "678912345",
                            Website = "www.auroramelodies.com"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bluewave Studio",
                            Nip = "321987654",
                            Regon = "789123456",
                            Website = "www.bluewavestudio.com"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cosmic Tunes",
                            Nip = "219876543",
                            Regon = "891234567",
                            Website = "www.cosmictunes.com"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dreamscape Audio",
                            Nip = "198765432",
                            Regon = "912345678",
                            Website = "www.dreamscapeaudio.com"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Eclipse Records",
                            Nip = "987654320",
                            Regon = "123456780",
                            Website = "www.eclipserecords.com"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fusion Beats",
                            Nip = "876543210",
                            Regon = "234567890",
                            Website = "www.fusionbeats.com"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Galaxy Grooves",
                            Nip = "765432109",
                            Regon = "345678901",
                            Website = "www.galaxygrooves.com"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Harmony Hub",
                            Nip = "654321098",
                            Regon = "456789012",
                            Website = "www.harmonyhub.com"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Infinity Sounds",
                            Nip = "543210987",
                            Regon = "567890123",
                            Website = "www.infinitysounds.com"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jazz Journey",
                            Nip = "432109876",
                            Regon = "678901234",
                            Website = "www.jazzjourney.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4556ff26-3c24-49ea-a5e3-6c65524c8140",
                            ConcurrencyStamp = "4556ff26-3c24-49ea-a5e3-6c65524c8140",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f146f123-4c28-434b-ba42-46acdf4ccca4",
                            ConcurrencyStamp = "f146f123-4c28-434b-ba42-46acdf4ccca4",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "97ca4a85-a0cc-4479-bb62-db3a16b85d9d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d641d9c-87f6-4ea6-9906-48190ff05691",
                            Email = "adam@wsei.edu.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADAM@WSEI.EDU.PL",
                            NormalizedUserName = "ADAM@WSEI.EDU.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEAN7Sryt5eCChe1iGWNdEC130gdUhhQOqY/W2YmG6fYSUr7BEddV+W2U0MScl8kF1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79279af2-e68f-4634-9d1e-c65f4d1204cd",
                            TwoFactorEnabled = false,
                            UserName = "adam@wsei.edu.pl"
                        },
                        new
                        {
                            Id = "47a364c9-1326-4d6c-8588-ecddc5561b75",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "345ccb41-788a-427a-a396-c45bb020d304",
                            Email = "jan@wsei.edu.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JAN@WSEI.EDU.PL",
                            NormalizedUserName = "JAN@WSEI.EDU.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEHk0bIFfTiWiEVnKP3o0iDPIwH+PU4bd3wfju3rZ22xh7JjHfcja2IKeziLSUeIgog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "736e24a9-03e2-44f8-9f4e-9bb0804d3c53",
                            TwoFactorEnabled = false,
                            UserName = "jan@wsei.edu.pl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "97ca4a85-a0cc-4479-bb62-db3a16b85d9d",
                            RoleId = "4556ff26-3c24-49ea-a5e3-6c65524c8140"
                        },
                        new
                        {
                            UserId = "47a364c9-1326-4d6c-8588-ecddc5561b75",
                            RoleId = "f146f123-4c28-434b-ba42-46acdf4ccca4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.AlbumEntity", b =>
                {
                    b.HasOne("Data.Entities.RecordLabelEntity", "RecordLabel")
                        .WithMany("Albums")
                        .HasForeignKey("RecordLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordLabel");
                });

            modelBuilder.Entity("Data.Entities.RecordLabelEntity", b =>
                {
                    b.OwnsOne("Data.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("RecordLabelEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ApartmentNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("RecordLabelEntityId");

                            b1.ToTable("recordlabel");

                            b1.WithOwner()
                                .HasForeignKey("RecordLabelEntityId");

                            b1.HasData(
                                new
                                {
                                    RecordLabelEntityId = 1,
                                    City = "Warszawa",
                                    Country = "Poland",
                                    HouseNumber = "27A",
                                    PostalCode = "00-639",
                                    State = "mazowieckie",
                                    Street = "Marszałkowska"
                                },
                                new
                                {
                                    RecordLabelEntityId = 2,
                                    City = "Gdańsk",
                                    Country = "Poland",
                                    HouseNumber = "45/6",
                                    PostalCode = "80-831",
                                    State = "pomorskie",
                                    Street = "Długa"
                                },
                                new
                                {
                                    RecordLabelEntityId = 3,
                                    City = "Wrocław",
                                    Country = "Poland",
                                    HouseNumber = "13",
                                    PostalCode = "50-101",
                                    State = "dolnośląskie",
                                    Street = "Rynek"
                                },
                                new
                                {
                                    RecordLabelEntityId = 4,
                                    City = "Kraków",
                                    Country = "Poland",
                                    HouseNumber = "39",
                                    PostalCode = "31-019",
                                    State = "małopolskie",
                                    Street = "Floriańska"
                                },
                                new
                                {
                                    RecordLabelEntityId = 5,
                                    City = "Poznań",
                                    Country = "Poland",
                                    HouseNumber = "80/82",
                                    PostalCode = "61-809",
                                    State = "wielkopolskie",
                                    Street = "Święty Marcin"
                                },
                                new
                                {
                                    RecordLabelEntityId = 6,
                                    City = "Warszawa",
                                    Country = "Poland",
                                    HouseNumber = "27A",
                                    PostalCode = "00-639",
                                    State = "mazowieckie",
                                    Street = "Marszałkowska"
                                },
                                new
                                {
                                    RecordLabelEntityId = 7,
                                    City = "Gdańsk",
                                    Country = "Poland",
                                    HouseNumber = "45/6",
                                    PostalCode = "80-831",
                                    State = "pomorskie",
                                    Street = "Długa"
                                },
                                new
                                {
                                    RecordLabelEntityId = 8,
                                    City = "Wrocław",
                                    Country = "Poland",
                                    HouseNumber = "13",
                                    PostalCode = "50-101",
                                    State = "dolnośląskie",
                                    Street = "Rynek"
                                },
                                new
                                {
                                    RecordLabelEntityId = 9,
                                    City = "Kraków",
                                    Country = "Poland",
                                    HouseNumber = "39",
                                    PostalCode = "31-019",
                                    State = "małopolskie",
                                    Street = "Floriańska"
                                },
                                new
                                {
                                    RecordLabelEntityId = 10,
                                    City = "Poznań",
                                    Country = "Poland",
                                    HouseNumber = "80/82",
                                    PostalCode = "61-809",
                                    State = "wielkopolskie",
                                    Street = "Święty Marcin"
                                },
                                new
                                {
                                    RecordLabelEntityId = 11,
                                    City = "Warszawa",
                                    Country = "Poland",
                                    HouseNumber = "27A",
                                    PostalCode = "00-639",
                                    State = "mazowieckie",
                                    Street = "Marszałkowska"
                                },
                                new
                                {
                                    RecordLabelEntityId = 12,
                                    City = "Gdańsk",
                                    Country = "Poland",
                                    HouseNumber = "45/6",
                                    PostalCode = "80-831",
                                    State = "pomorskie",
                                    Street = "Długa"
                                },
                                new
                                {
                                    RecordLabelEntityId = 13,
                                    City = "Wrocław",
                                    Country = "Poland",
                                    HouseNumber = "13",
                                    PostalCode = "50-101",
                                    State = "dolnośląskie",
                                    Street = "Rynek"
                                },
                                new
                                {
                                    RecordLabelEntityId = 14,
                                    City = "Kraków",
                                    Country = "Poland",
                                    HouseNumber = "39",
                                    PostalCode = "31-019",
                                    State = "małopolskie",
                                    Street = "Floriańska"
                                },
                                new
                                {
                                    RecordLabelEntityId = 15,
                                    City = "Poznań",
                                    Country = "Poland",
                                    HouseNumber = "80/82",
                                    PostalCode = "61-809",
                                    State = "wielkopolskie",
                                    Street = "Święty Marcin"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.RecordLabelEntity", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
